# site settings
title: Dmytro Naida
subtitle: Product Manager
email: dmytro.naida@icloud.com
description: My naida is Dima Naida and I'm a Sr. Product Manager at AutoScout24. Prior to that, I was working as a PM at Red Bull Media House, developing action sports games for mobile. I come from Ukraine 🇺🇦 and do CrossFit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dmytronaida.com" # the base hostname & protocol for your site
author: Dmytro Naida
city: Munich
country: Germany

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
facebook_url: https://www.facebook.com/dmytro.naida
github_url: https://github.com/dmytronayda
linkedin_url: https://www.linkedin.com/in/dmytro-naida

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
