# site settings
title: Forty
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Dmytro Naida

city: Salzburg
country: Austria
phone: +43 66488340832

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/dmytro.naida
github_url: https://github.com/dmytronayda
instagram_url: https://www.instagram.com/cadet_93/
linkedin_url: https://www.linkedin.com/in/dmytro-naida/

# build settings
markdown: kramdown

sass:
  style: compressed
